name: Test Develop

on:
  pull_request:
    branches: [develop]

jobs:
  build-test:
    if: github.event.pull_request.draft == false
    runs-on: neodash-runners
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Creating Neo4j Container
        run: |
          chmod +x apps/neodash-editor/docker-files/docker-neo4j-initializer/docker-neo4j.sh
          apps/neodash-editor/docker-files/docker-neo4j-initializer/docker-neo4j.sh
          sleep 30s
          chmod +x apps/neodash-editor/docker-files/docker-neo4j-initializer/start-movies-db.sh
          apps/neodash-editor/docker-files/docker-neo4j-initializer/start-movies-db.sh
      - run: yarn global add turbo
      - run: yarn install
      - name: Eslint check
        run: yarn lint:all
      - name: Copy cypress config to root folder for execution
        run: cp -r apps/neodash-editor/cypress .
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config-file: apps/neodash-editor/cypress-config.ts
          build: yarn build:editor
          start: yarn start:editor
          wait-on: "http://localhost:3000"
          browser: chrome
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
